import { db, TipoCategoria, TipoSubCategoria } from "astro:db";

// https://astro.build/db/seed

export default async function seedCategoriasTransacciones() {
  const categoriasInsertadas = await db
    .insert(TipoCategoria)
    .values([
      {
        nombre: "Comida y Bebida",
        icono: "cubiertos",
        color: "red",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Compras",
        icono: "bolso",
        color: "lightblue",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Vivienda",
        icono: "casa",
        color: "orange",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Transporte",
        icono: "colectivo",
        color: "grey",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Vehículos",
        icono: "auto",
        color: "violet",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Vida y Entretenimiento",
        icono: "persona",
        color: "green",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Comunicaciones, PC",
        icono: "monitor",
        color: "blue",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Gastos Financieros",
        icono: "monedas_dobles",
        color: "cyan",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Inversiones",
        icono: "moneda_conectada",
        color: "fucsia",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
      {
        nombre: "Ingreso",
        icono: "monedas_aplidas",
        color: "yellow",
        createUser: "gvidart",
        updateUser: "gvidart",
      },
    ])
    .returning({ insertedId: TipoCategoria.id });

  await db.insert(TipoSubCategoria).values([
    //----------------------------
    {
      nombre: "Bar y Café",
      icono: "copa",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(0)!.insertedId,
    },
    {
      nombre: "Restaurante, comida Rápida",
      icono: "restaurant",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(0)!.insertedId,
    },
    {
      nombre: "Supermercados",
      icono: "supermercado",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(0)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Bebés, niños",
      icono: "carrito_bebe",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Casa y Jardín",
      icono: "casa",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Electrónica",
      icono: "computadora",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Farmacia",
      icono: "farmacia",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Joyas",
      icono: "joya",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Mascotas, animales",
      icono: "pata_animal",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Herramientas",
      icono: "herramientas",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Librería",
      icono: "libreria",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Regalos",
      icono: "regalo",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Ropa y Calzado",
      icono: "ropa",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Salud",
      icono: "salud",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },
    {
      nombre: "Tiempo Libre",
      icono: "tiempo_libre",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(1)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Hipoteca",
      icono: "casa_peso",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(2)!.insertedId,
    },
    {
      nombre: "Mantenimiento, reparaciones",
      icono: "martillo",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(2)!.insertedId,
    },
    {
      nombre: "Alquiler",
      icono: "llave",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(2)!.insertedId,
    },
    {
      nombre: "Seguro de propiedad",
      icono: "seguro_casa",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(2)!.insertedId,
    },
    {
      nombre: "Servicios",
      icono: "boleta_servicio",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(2)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Larga Distancia",
      icono: "avion",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },
    {
      nombre: "Taxi",
      icono: "taxi",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },
    {
      nombre: "Tren",
      icono: "tren",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },
    {
      nombre: "Colectivo",
      icono: "colectivo",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },
    {
      nombre: "Uber",
      icono: "uber",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },
    {
      nombre: "Cabify",
      icono: "cabify",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },
    {
      nombre: "Bicicleta",
      icono: "bicicleta",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(3)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Alquiler",
      icono: "monedas_horizontal",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(4)!.insertedId,
    },
    {
      nombre: "Combustible",
      icono: "estacion_servicio",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(4)!.insertedId,
    },
    {
      nombre: "Estacionamiento",
      icono: "parking",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(4)!.insertedId,
    },
    {
      nombre: "Mantenimiento Vehículo",
      icono: "llave_inglesa",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(4)!.insertedId,
    },
    {
      nombre: "Seguro Vehículo",
      icono: "seguro_auto",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(4)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Alcohol, tabaco",
      icono: "botella_alcohol",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Bienestar",
      icono: "flor",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Caridad, regalos",
      icono: "regalo",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Médico, estudios",
      icono: "doctor",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Cultura",
      icono: "arte",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Evento Musical",
      icono: "escenario_festival",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Deporte, fitness",
      icono: "mancuerna",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Educación, desarrollo",
      icono: "universitario",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Eventos Especiales",
      icono: "torta_cumpleanios",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Libros, audio, suscripciones",
      icono: "Libro",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Lotería, juegos de azar",
      icono: "dado",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Pasatiempos",
      icono: "corazon",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "TV, Streaming",
      icono: "tv",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Vacaciones",
      icono: "montaña",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },
    {
      nombre: "Hotel",
      icono: "hotel",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(5)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Internet",
      icono: "wifi",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(6)!.insertedId,
    },
    {
      nombre: "Correo",
      icono: "cartero",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(6)!.insertedId,
    },
    {
      nombre: "Software",
      icono: "software",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(6)!.insertedId,
    },
    {
      nombre: "Aplicaciones",
      icono: "app",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(6)!.insertedId,
    },
    {
      nombre: "Juegos",
      icono: "juegos",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(6)!.insertedId,
    },
    {
      nombre: "Teléfono Móvil",
      icono: "celular",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(6)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Asesoramiento",
      icono: "persona_hablando",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(7)!.insertedId,
    },
    {
      nombre: "Impuestos",
      icono: "billete_cortado",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(7)!.insertedId,
    },
    {
      nombre: "Multas",
      icono: "policia",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(7)!.insertedId,
    },
    {
      nombre: "Préstamos, intereses",
      icono: "billetes",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(7)!.insertedId,
    },
    {
      nombre: "Seguros",
      icono: "seguro",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(7)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Ahorros",
      icono: "bolsa_dinero",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(8)!.insertedId,
    },
    {
      nombre: "Bienes Raíces",
      icono: "edificios",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(8)!.insertedId,
    },
    {
      nombre: "Criptomonedas",
      icono: "btc_eth",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(8)!.insertedId,
    },
    {
      nombre: "Plazo Fijo",
      icono: "banco",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(8)!.insertedId,
    },
    {
      nombre: "Compra Dólares",
      icono: "dolar",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(8)!.insertedId,
    },

    //----------------------------
    {
      nombre: "Cheques, cupones",
      icono: "cheque",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Cuotas",
      icono: "item_check",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Ingesos por alquiler",
      icono: "casa_peso",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Intereses, dividendos",
      icono: "billete_porcentaje",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Lotería, juegos de azar",
      icono: "dado",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Reembolsos",
      icono: "arrow_return",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Regalos",
      icono: "sobre_billete",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Salario",
      icono: "recibe_dinero",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
    {
      nombre: "Venta",
      icono: "billetera",
      createUser: "gvidart",
      updateUser: "gvidart",
      idCategoria: categoriasInsertadas.at(9)!.insertedId,
    },
  ]);
}
